/**
 * HTML Report Generator — produces a self-contained, interactive report.
 *
 * Key improvements over original:
 *   - Template-based generation (no ad-hoc string concat)
 *   - HTML entity escaping to prevent XSS
 *   - Responsive design with modern CSS
 *   - Client-side sorting, filtering, and search
 *   - Color-coded complexity indicators
 *   - Collapsible duplicate groups
 */
const path = require('path');
const { getDuplicateFilePaths } = require('./analyzers/duplicates');

/**
 * Escape HTML entities to prevent XSS in generated reports.
 */
function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Return a CSS class based on complexity score.
 */
function complexityClass(score) {
  if (score <= 5) return 'complexity-low';
  if (score <= 15) return 'complexity-medium';
  if (score <= 30) return 'complexity-high';
  return 'complexity-critical';
}

/**
 * Generate the full HTML report.
 */
function generateReport({ projectName, summary, results, duplicateGroups, columns }) {
  const duplicatePaths = getDuplicateFilePaths(duplicateGroups);
  const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 19);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>TS Analysis — ${escapeHtml(projectName)}</title>
<style>
${CSS}
</style>
</head>
<body>

<header>
  <h1>TypeScript Analysis Report</h1>
  <p class="subtitle">${escapeHtml(projectName)} &middot; ${timestamp}</p>
</header>

<section class="summary">
  <div class="metric">
    <span class="metric-value">${summary.totalFiles}</span>
    <span class="metric-label">Files</span>
  </div>
  <div class="metric">
    <span class="metric-value">${summary.totalLines.toLocaleString()}</span>
    <span class="metric-label">Total Lines</span>
  </div>
  ${summary.totalFunctions !== null ? `
  <div class="metric">
    <span class="metric-value">${summary.totalFunctions}</span>
    <span class="metric-label">Functions</span>
  </div>` : ''}
  ${summary.totalComplexity !== null ? `
  <div class="metric">
    <span class="metric-value">${summary.totalComplexity}</span>
    <span class="metric-label">Complexity (${escapeHtml(summary.complexityLevel)})</span>
  </div>` : ''}
  ${duplicateGroups.length > 0 ? `
  <div class="metric metric-warn">
    <span class="metric-value">${duplicateGroups.length}</span>
    <span class="metric-label">Duplicate Groups</span>
  </div>` : ''}
</section>

${duplicateGroups.length > 0 ? renderDuplicates(duplicateGroups) : ''}

<section class="table-section">
  <div class="table-controls">
    <input type="text" id="search" placeholder="Filter files..." oninput="filterTable()">
  </div>
  <table id="analysis-table">
    <thead>
      <tr>
        <th onclick="sortTable(0)">File ⇅</th>
        <th onclick="sortTable(1)">Lines ⇅</th>
        ${columns.functions ? '<th onclick="sortTable(2)">Functions ⇅</th>' : ''}
        <th onclick="sortTable(${columns.functions ? 3 : 2})">Dependencies ⇅</th>
        ${columns.complexity ? `<th onclick="sortTable(${columns.functions ? 4 : 3})">Complexity ⇅</th>` : ''}
      </tr>
    </thead>
    <tbody>
      ${results.map(r => renderRow(r, columns, duplicatePaths)).join('\n')}
    </tbody>
  </table>
</section>

<footer>
  <p>Generated by ts-analyzer</p>
</footer>

<script>
${SCRIPT}
</script>
</body>
</html>`;
}

function renderDuplicates(groups) {
  const items = groups.map(g => {
    const fileList = g.files.map(f => `<li>${escapeHtml(f)}</li>`).join('');
    return `<details>
      <summary>${g.files.length} identical files (hash: ${g.hash.slice(0, 12)}…)</summary>
      <ul>${fileList}</ul>
    </details>`;
  }).join('\n');

  return `
  <section class="duplicates">
    <h2>⚠ Duplicate Files</h2>
    ${items}
  </section>`;
}

function renderRow(result, columns, duplicatePaths) {
  const isDuplicate = duplicatePaths.has(result.filePath);
  const cls = isDuplicate ? ' class="duplicate"' : '';
  const cxClass = columns.complexity ? ` ${complexityClass(result.complexity)}` : '';

  let cells = `
    <td title="${escapeHtml(result.filePath)}">${escapeHtml(result.fileName)}</td>
    <td>${result.totalLines}</td>`;

  if (columns.functions) {
    cells += `<td>${result.functionCount}</td>`;
  }

  cells += `<td class="deps">${result.dependencies.map(d => escapeHtml(d)).join(', ') || '—'}</td>`;

  if (columns.complexity) {
    cells += `<td class="${cxClass}">${result.complexity}</td>`;
  }

  return `<tr${cls}>${cells}</tr>`;
}

// ── Embedded CSS ─────────────────────────────────────────────
const CSS = `
:root {
  --bg: #f8f9fa;
  --surface: #ffffff;
  --border: #e2e8f0;
  --text: #1a202c;
  --text-muted: #718096;
  --accent: #3182ce;
  --warn: #e53e3e;
  --success: #38a169;
}

* { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
  padding: 2rem;
  max-width: 1400px;
  margin: 0 auto;
}

header {
  margin-bottom: 2rem;
}

h1 { font-size: 1.75rem; font-weight: 700; }
h2 { font-size: 1.25rem; font-weight: 600; margin-bottom: 0.75rem; }

.subtitle { color: var(--text-muted); margin-top: 0.25rem; }

.summary {
  display: flex;
  gap: 1.5rem;
  flex-wrap: wrap;
  margin-bottom: 2rem;
}

.metric {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1rem 1.5rem;
  min-width: 140px;
  text-align: center;
}

.metric-value {
  display: block;
  font-size: 1.75rem;
  font-weight: 700;
  color: var(--accent);
}

.metric-warn .metric-value { color: var(--warn); }

.metric-label {
  display: block;
  font-size: 0.8rem;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.05em;
  margin-top: 0.25rem;
}

.duplicates {
  background: #fff5f5;
  border: 1px solid #fed7d7;
  border-radius: 8px;
  padding: 1.5rem;
  margin-bottom: 2rem;
}

.duplicates details { margin: 0.5rem 0; }
.duplicates summary { cursor: pointer; font-weight: 500; }
.duplicates ul { margin: 0.5rem 0 0 1.5rem; font-size: 0.9rem; color: var(--text-muted); }

.table-section {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 8px;
  overflow: hidden;
}

.table-controls {
  padding: 1rem;
  border-bottom: 1px solid var(--border);
}

#search {
  width: 100%;
  max-width: 400px;
  padding: 0.5rem 0.75rem;
  border: 1px solid var(--border);
  border-radius: 6px;
  font-size: 0.9rem;
  outline: none;
}

#search:focus { border-color: var(--accent); box-shadow: 0 0 0 3px rgba(49,130,206,0.15); }

table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.9rem;
}

th {
  background: var(--bg);
  padding: 0.75rem 1rem;
  text-align: left;
  font-weight: 600;
  cursor: pointer;
  user-select: none;
  white-space: nowrap;
  border-bottom: 2px solid var(--border);
}

th:hover { background: #edf2f7; }

td {
  padding: 0.5rem 1rem;
  border-bottom: 1px solid var(--border);
}

td.deps {
  max-width: 300px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-size: 0.8rem;
  color: var(--text-muted);
}

tr:hover { background: #f7fafc; }
tr.duplicate { background: #fff5f5; }
tr.duplicate:hover { background: #fed7d7; }

.complexity-low { color: var(--success); font-weight: 600; }
.complexity-medium { color: #d69e2e; font-weight: 600; }
.complexity-high { color: #dd6b20; font-weight: 700; }
.complexity-critical { color: var(--warn); font-weight: 700; }

footer {
  margin-top: 2rem;
  text-align: center;
  font-size: 0.8rem;
  color: var(--text-muted);
}

@media (max-width: 768px) {
  body { padding: 1rem; }
  .summary { gap: 0.75rem; }
  .metric { min-width: 100px; padding: 0.75rem; }
  td.deps { max-width: 150px; }
}
`;

// ── Embedded JavaScript ──────────────────────────────────────
const SCRIPT = `
function sortTable(colIndex) {
  const table = document.getElementById('analysis-table');
  const tbody = table.querySelector('tbody');
  const rows = Array.from(tbody.querySelectorAll('tr'));
  const th = table.querySelectorAll('th')[colIndex];

  // Toggle sort direction
  const asc = th.dataset.sort !== 'asc';
  table.querySelectorAll('th').forEach(h => delete h.dataset.sort);
  th.dataset.sort = asc ? 'asc' : 'desc';

  rows.sort((a, b) => {
    const va = a.cells[colIndex]?.textContent.trim() ?? '';
    const vb = b.cells[colIndex]?.textContent.trim() ?? '';
    const na = parseFloat(va), nb = parseFloat(vb);
    if (!isNaN(na) && !isNaN(nb)) return asc ? na - nb : nb - na;
    return asc ? va.localeCompare(vb) : vb.localeCompare(va);
  });

  rows.forEach(r => tbody.appendChild(r));
}

function filterTable() {
  const query = document.getElementById('search').value.toLowerCase();
  const rows = document.querySelectorAll('#analysis-table tbody tr');
  rows.forEach(row => {
    const text = row.textContent.toLowerCase();
    row.style.display = text.includes(query) ? '' : 'none';
  });
}
`;

module.exports = { generateReport };
